### ISSUE TITLE
Unable to access the link to download the QEMU image

### ISSUE THREAD

**Issue by phoenix329** [Dantali0n/OpenCSD#5]
Hello, I am unable to access the link to the QEMU image you provided. The page shows a "Page Not Found" error message. The page either cannot be found on the server or you may not have permission to browse it. Is there a new address for the image available now?

**Comment by Dantali0n** [comment]
Yes, nextcloud has changed the url pattern for there shares, I have yet to update the URLs in OpenCSD

**Comment by Dantali0n** [comment]
Thesis can be found here: https://nextcloud.dantalion.nl/s/dN7KZTSSyxx2Xw4

**Comment by Dantali0n** [comment]
Fixed in f4d23d36fef37646d3b86ca1150039019560e5be

**Comment by phoenix329** [comment]
> Fixed in [f4d23d3](https://github.com/Dantali0n/OpenCSD/commit/f4d23d36fef37646d3b86ca1150039019560e5be)

Thank you for your help. Now aI am able to download “.torrent” file, I cannot find any resources to download the ".qcow2" file by Bitcomet. I will try other methods.

**Comment by Dantali0n** [comment]
You can download from this link directly: https://nextcloud.dantalion.nl/s/diW4CrE7gfgLqxe/download

**Comment by phoenix329** [comment]
> You can download from this link directly: https://nextcloud.dantalion.nl/s/diW4CrE7gfgLqxe/download

Thank you very much for your help. I have successfully downloaded the image file.
